// web/src/routes/register/+page.svelte
<script lang="ts">
  import { auth } from '$lib/firebase/config';
  import { createUserWithEmailAndPassword, updateProfile } from 'firebase/auth';
  import { goto } from '$app/navigation';

  let email = '';
  let password = '';
  let displayName = '';
  let error = '';
  let loading = false;

  async function register() {
    if (!email || !password || !displayName) { error = 'Tüm alanları doldurun.'; return; }
    loading = true; error = '';
    try {
      const cred = await createUserWithEmailAndPassword(auth, email, password);
      await updateProfile(cred.user, { displayName });
      goto('/feed');
    } catch (e: any) {
      error = e.code === 'auth/email-already-in-use' ? 'Bu e-posta zaten kullanımda.' : 'Kayıt başarısız.';
    } finally {
      loading = false;
    }
  }
</script>

<div class="auth-wrap">
  <div class="auth-card">
    <h1 class="logo">Heftreng</h1>
    <p class="subtitle">Hesap oluştur</p>

    {#if error}
      <div class="error-box">{error}</div>
    {/if}

    <div class="field">
      <label>Ad Soyad</label>
      <input type="text" bind:value={displayName} placeholder="Adın Soyadın" />
    </div>

    <div class="field">
      <label>E-posta</label>
      <input type="email" bind:value={email} placeholder="ornek@mail.com" />
    </div>

    <div class="field">
      <label>Şifre</label>
      <input type="password" bind:value={password} placeholder="En az 6 karakter" />
    </div>

    <button class="btn-primary" on:click={register} disabled={loading}>
      {loading ? 'Kayıt yapılıyor...' : 'Kayıt Ol'}
    </button>

    <p class="footer-text">
      Zaten hesabın var mı? <a href="/login">Giriş Yap</a>
    </p>
  </div>
</div>

<style>
.auth-wrap {
  min-height: 100vh; display: flex;
  align-items: center; justify-content: center;
  background: var(--bg); padding: 20px;
}
.auth-card {
  background: var(--surface); border-radius: 20px;
  padding: 32px 28px; width: 100%; max-width: 380px;
  border: 1px solid var(--divider);
}
.logo {
  font-family: 'Playfair Display', serif;
  font-size: 28px; color: var(--primary);
  text-align: center; margin-bottom: 4px;
}
.subtitle { text-align: center; color: var(--muted); font-size: 14px; margin-bottom: 24px; }
.field { margin-bottom: 16px; }
.field label { display: block; font-size: 13px; color: var(--muted); margin-bottom: 6px; }
.field input {
  width: 100%; padding: 12px 14px;
  background: var(--surface-var); border: 1px solid var(--divider);
  border-radius: 12px; color: var(--on-bg); font-size: 15px; outline: none;
}
.field input:focus { border-color: var(--primary); }
.btn-primary {
  width: 100%; padding: 14px;
  background: var(--primary); color: #fff;
  border-radius: 12px; font-size: 16px; font-weight: 600;
  margin-top: 8px; transition: opacity 0.2s;
}
.btn-primary:disabled { opacity: 0.6; }
.error-box {
  background: rgba(248,113,113,0.1); border: 1px solid var(--error);
  color: var(--error); border-radius: 10px; padding: 10px 14px;
  font-size: 14px; margin-bottom: 16px;
}
.footer-text { text-align: center; margin-top: 20px; font-size: 14px; color: var(--muted); }
.footer-text a { color: var(--primary); font-weight: 600; }
</style>

// web/src/app/(auth)/register/page.tsx
"use client"
import { useState }   from "react"
import Link            from "next/link"
import { useRouter }   from "next/navigation"
import { signUp }      from "@/lib/hooks/useAuth"
import toast           from "react-hot-toast"

export default function RegisterPage() {
  const router = useRouter()
  const [displayName, setDisplayName] = useState("")
  const [username,    setUsername]    = useState("")
  const [email,       setEmail]       = useState("")
  const [password,    setPassword]    = useState("")
  const [loading,     setLoading]     = useState(false)

  const handleSubmit = async () => {
    if (!displayName || !username || !email || !password) return
    if (password.length < 6) { toast.error("Şifre en az 6 karakter olmalı"); return }
    setLoading(true)
    try {
      await signUp(email, password, username, displayName)
      router.push("/feed")
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : ""
      toast.error(msg.includes("email-already-in-use") ? "Bu e-posta zaten kullanımda" : "Kayıt başarısız")
    } finally {
      setLoading(false)
    }
  }

  const fields = [
    { label: "Ad Soyad", value: displayName, set: setDisplayName, type: "text",     placeholder: "Adın Soyadın" },
    { label: "Kullanıcı Adı", value: username, set: setUsername,  type: "text",     placeholder: "kullanici_adi" },
    { label: "E-posta",   value: email,       set: setEmail,       type: "email",    placeholder: "ornek@mail.com" },
    { label: "Şifre",     value: password,    set: setPassword,    type: "password", placeholder: "En az 6 karakter" },
  ]

  return (
    <div className="min-h-screen flex items-center justify-center px-4" style={{ background: "var(--bg)" }}>
      <div
        className="w-full max-w-sm rounded-2xl p-8 border"
        style={{ background: "var(--surface)", borderColor: "var(--divider)" }}
      >
        <h1
          className="text-2xl font-bold mb-1 grad-text"
          style={{ fontFamily: "Playfair Display, serif" }}
        >
          Heftreng
        </h1>
        <p className="text-sm mb-6" style={{ color: "var(--muted)" }}>Yeni hesap oluştur</p>

        <div className="flex flex-col gap-3">
          {fields.map(({ label, value, set, type, placeholder }) => (
            <input
              key={label}
              type={type}
              placeholder={placeholder}
              value={value}
              onChange={(e) => set(e.target.value)}
              className="w-full px-4 py-3 rounded-xl text-sm outline-none border transition-colors focus:border-[var(--primary)]"
              style={{ background: "var(--surface-var)", borderColor: "var(--divider)", color: "var(--on-bg)" }}
            />
          ))}

          <button
            onClick={handleSubmit}
            disabled={loading || !displayName || !username || !email || !password}
            className="w-full py-3 rounded-xl text-sm font-semibold transition-all disabled:opacity-50 mt-1"
            style={{ background: "var(--primary)", color: "var(--bg)" }}
          >
            {loading ? (
              <span className="inline-block w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin" />
            ) : "Kayıt Ol"}
          </button>
        </div>

        <p className="text-center text-sm mt-5" style={{ color: "var(--muted)" }}>
          Hesabın var mı?{" "}
          <Link href="/login" style={{ color: "var(--primary)" }} className="font-medium hover:underline">
            Giriş Yap
          </Link>
        </p>
      </div>
    </div>
  )
}
