// web/src/app/(auth)/login/page.tsx
"use client"
import { useState } from "react"
import Link         from "next/link"
import { useRouter } from "next/navigation"
import { signIn }   from "@/lib/hooks/useAuth"
import toast        from "react-hot-toast"

export default function LoginPage() {
  const router = useRouter()
  const [email,    setEmail]    = useState("")
  const [password, setPassword] = useState("")
  const [loading,  setLoading]  = useState(false)

  const handleSubmit = async () => {
    if (!email || !password) return
    setLoading(true)
    try {
      await signIn(email, password)
      router.push("/feed")
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : "Giriş başarısız"
      toast.error(msg.includes("wrong-password") ? "Şifre hatalı" :
                  msg.includes("user-not-found") ? "Kullanıcı bulunamadı" : "Bir hata oluştu")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center px-4" style={{ background: "var(--bg)" }}>
      <div
        className="w-full max-w-sm rounded-2xl p-8 border"
        style={{ background: "var(--surface)", borderColor: "var(--divider)" }}
      >
        <h1
          className="text-2xl font-bold mb-1 grad-text"
          style={{ fontFamily: "Playfair Display, serif" }}
        >
          Heftreng
        </h1>
        <p className="text-sm mb-6" style={{ color: "var(--muted)" }}>Hesabına giriş yap</p>

        <div className="flex flex-col gap-3">
          <input
            type="email"
            placeholder="E-posta"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="w-full px-4 py-3 rounded-xl text-sm outline-none border transition-colors focus:border-[var(--primary)]"
            style={{
              background:  "var(--surface-var)",
              borderColor: "var(--divider)",
              color:       "var(--on-bg)",
            }}
          />
          <input
            type="password"
            placeholder="Şifre"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleSubmit()}
            className="w-full px-4 py-3 rounded-xl text-sm outline-none border transition-colors focus:border-[var(--primary)]"
            style={{
              background:  "var(--surface-var)",
              borderColor: "var(--divider)",
              color:       "var(--on-bg)",
            }}
          />
          <button
            onClick={handleSubmit}
            disabled={loading || !email || !password}
            className="w-full py-3 rounded-xl text-sm font-semibold transition-all disabled:opacity-50 mt-1"
            style={{ background: "var(--primary)", color: "var(--bg)" }}
          >
            {loading ? (
              <span className="inline-block w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin" />
            ) : "Giriş Yap"}
          </button>
        </div>

        <p className="text-center text-sm mt-5" style={{ color: "var(--muted)" }}>
          Hesabın yok mu?{" "}
          <Link href="/register" style={{ color: "var(--primary)" }} className="font-medium hover:underline">
            Kayıt Ol
          </Link>
        </p>
      </div>
    </div>
  )
}

// web/src/routes/login/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { signIn } from '$lib/services/auth.service';

  let email    = $state('');
  let password = $state('');
  let error    = $state('');
  let loading  = $state(false);

  async function login() {
    if (!email || !password) return;
    loading = true; error = '';
    try {
      await signIn(email, password);
      goto('/feed');
    } catch(e: any) {
      error =
        e.code === 'auth/invalid-credential' || e.code === 'auth/wrong-password'
          ? 'E-posta veya şifre hatalı.'
          : e.code === 'auth/user-not-found'
          ? 'Bu e-posta kayıtlı değil.'
          : e.code === 'auth/too-many-requests'
          ? 'Çok fazla deneme. Lütfen bekleyin.'
          : (e.message ?? 'Giriş başarısız.');
    } finally { loading = false; }
  }
</script>

<div class="wrap">
  <div class="card">
    <h1 class="logo">Heftreng</h1>
    <p class="sub">Kürt edebiyatı ve dil topluluğu</p>
    {#if error}<div class="err">{error}</div>{/if}
    <div class="field"><label for="email">E-posta</label><input id="email" type="email" bind:value={email} placeholder="ornek@mail.com"/></div>
    <div class="field"><label for="pass">Şifre</label><input id="pass" type="password" bind:value={password} placeholder="••••••••"/></div>
    <button class="btn" onclick={login} disabled={loading}>{loading ? 'Giriş yapılıyor...' : 'Giriş Yap'}</button>
    <p class="foot">Hesabın yok mu? <a href="/register">Kayıt Ol</a></p>
  </div>
</div>

<style>
.wrap { min-height:100vh; display:flex; align-items:center; justify-content:center; background:var(--bg); padding:20px; }
.card { background:var(--surface); border-radius:20px; padding:32px 28px; width:100%; max-width:380px; border:1px solid var(--divider); }
.logo { font-family:'Playfair Display',serif; font-size:28px; color:var(--primary); text-align:center; margin-bottom:4px; }
.sub { text-align:center; color:var(--muted); font-size:14px; margin-bottom:24px; }
.field { margin-bottom:16px; }
.field label { display:block; font-size:13px; color:var(--muted); margin-bottom:6px; }
.field input { width:100%; padding:12px 14px; background:var(--surface-var); border:1px solid var(--divider); border-radius:12px; color:var(--on-bg); font-size:15px; outline:none; }
.field input:focus { border-color:var(--primary); }
.btn { width:100%; padding:14px; background:var(--primary); color:#fff; border-radius:12px; font-size:16px; font-weight:600; margin-top:8px; cursor:pointer; border:none; }
.btn:disabled { opacity:0.6; }
.err { background:rgba(248,113,113,0.1); border:1px solid var(--error); color:var(--error); border-radius:10px; padding:10px 14px; font-size:14px; margin-bottom:16px; }
.foot { text-align:center; margin-top:20px; font-size:14px; color:var(--muted); }
.foot a { color:var(--primary); font-weight:600; }
</style>
