// web/src/components/feed/PostCard.tsx
"use client"
import Link from "next/link"
import Image from "next/image"
import { formatDistanceToNow } from "date-fns"
import { tr } from "date-fns/locale"
import { Heart, MessageCircle, Repeat2, Share2, MoreHorizontal } from "lucide-react"
import { Avatar } from "@/components/ui/Avatar"
import type { Post } from "@/lib/types"

interface Props {
  post:       Post
  onLike?:    (id: string) => void
  onComment?: (id: string) => void
  onRepost?:  (id: string) => void
  onDelete?:  (id: string) => void
  liked?:     boolean
  currentUid?: string
}

export function PostCard({ post, onLike, onComment, onRepost, liked, currentUid }: Props) {
  const time = formatDistanceToNow(new Date(post.ts), { addSuffix: true, locale: tr })

  return (
    <article
      className="border-b px-4 py-4 transition-colors hover:bg-[var(--surface-var)]"
      style={{ borderColor: "var(--divider)" }}
    >
      <div className="flex gap-3">
        {/* Avatar */}
        <Link href={`/profile/${post.uid}`} className="shrink-0">
          <Avatar src={post.photoURL} name={post.displayName} size={42} />
        </Link>

        <div className="flex-1 min-w-0">
          {/* Header */}
          <div className="flex items-center gap-1.5 flex-wrap">
            <Link
              href={`/profile/${post.uid}`}
              className="font-semibold text-sm hover:underline"
              style={{ color: "var(--on-bg)" }}
            >
              {post.isAnonymous ? "Anonim" : post.displayName}
            </Link>
            {!post.isAnonymous && (
              <span className="text-xs" style={{ color: "var(--muted)" }}>
                @{post.username}
              </span>
            )}
            <span style={{ color: "var(--muted)" }}>·</span>
            <span className="text-xs" style={{ color: "var(--muted)" }}>{time}</span>
          </div>

          {/* Gönderi metni */}
          <Link href={`/post/${post.id}`}>
            <p
              className="mt-1 text-sm leading-relaxed whitespace-pre-wrap break-words"
              style={{ color: "var(--on-bg)" }}
            >
              {post.body}
            </p>
          </Link>

          {/* Resimler */}
          {post.imageUrls?.length > 0 && (
            <div className={`mt-3 grid gap-1 rounded-xl overflow-hidden ${post.imageUrls.length > 1 ? "grid-cols-2" : "grid-cols-1"}`}>
              {post.imageUrls.slice(0, 4).map((url, i) => (
                <div key={i} className="relative aspect-video bg-[var(--shimmer)]">
                  <Image src={url} alt="" fill className="object-cover" />
                </div>
              ))}
            </div>
          )}

          {/* Aksiyonlar */}
          <div className="flex items-center gap-5 mt-3">
            <button
              onClick={() => onComment?.(post.id)}
              className="flex items-center gap-1.5 text-xs transition-colors hover:text-[var(--primary)]"
              style={{ color: "var(--muted)" }}
            >
              <MessageCircle size={16} />
              {post.commentCount > 0 && post.commentCount}
            </button>

            <button
              onClick={() => onRepost?.(post.id)}
              className="flex items-center gap-1.5 text-xs transition-colors hover:text-[var(--success)]"
              style={{ color: "var(--muted)" }}
            >
              <Repeat2 size={16} />
              {post.repostCount > 0 && post.repostCount}
            </button>

            <button
              onClick={() => onLike?.(post.id)}
              className="flex items-center gap-1.5 text-xs transition-colors"
              style={{ color: liked ? "var(--error)" : "var(--muted)" }}
            >
              <Heart size={16} fill={liked ? "currentColor" : "none"} />
              {post.likeCount > 0 && post.likeCount}
            </button>

            <button
              className="flex items-center gap-1.5 text-xs transition-colors hover:text-[var(--primary)]"
              style={{ color: "var(--muted)" }}
            >
              <Share2 size={16} />
            </button>
          </div>
        </div>
      </div>
    </article>
  )
}

// web/src/lib/components/PostCard.svelte
<script lang="ts">
  import type { Post } from '$lib/types';
  export let post: Post;

  function timeAgo(ts: number): string {
    const diff = Date.now() - ts;
    const m = Math.floor(diff / 60000);
    if (m < 1)  return 'şimdi';
    if (m < 60) return `${m}d`;
    const h = Math.floor(m / 60);
    if (h < 24) return `${h}sa`;
    return `${Math.floor(h / 24)}g`;
  }
</script>

<article class="card">
  <div class="card-header">
    <div class="avatar-wrap">
      {#if post.photoURL}
        <img src={post.photoURL} alt={post.displayName} class="avatar" />
      {:else}
        <div class="avatar-placeholder">{post.displayName?.[0] ?? '?'}</div>
      {/if}
    </div>
    <div class="meta">
      <div class="display-name">
        {post.isAnonymous ? 'Anonim' : post.displayName}
      </div>
      <div class="username-time">
        {#if !post.isAnonymous}<span>@{post.username}</span>{/if}
        <span class="time">{timeAgo(post.ts)}</span>
      </div>
    </div>
  </div>

  <p class="body">{post.body}</p>

  {#if post.imageUrls?.length}
    <div class="images">
      {#each post.imageUrls as url}
        <img src={url} alt="gönderi" class="post-img" />
      {/each}
    </div>
  {/if}

  <div class="actions">
    <button class="action-btn">❤️ {post.likeCount}</button>
    <button class="action-btn">💬 {post.commentCount}</button>
    <button class="action-btn">🔁 {post.repostCount}</button>
  </div>
</article>

<style>
.card {
  background: var(--card);
  border-bottom: 1px solid var(--divider);
  padding: 14px 16px;
}
.card-header { display: flex; gap: 10px; margin-bottom: 10px; }
.avatar, .avatar-placeholder {
  width: 40px; height: 40px;
  border-radius: 50%; object-fit: cover; flex-shrink: 0;
}
.avatar-placeholder {
  background: var(--primary); color: #fff;
  display: flex; align-items: center; justify-content: center;
  font-weight: 700; font-size: 16px;
}
.meta { display: flex; flex-direction: column; justify-content: center; }
.display-name { font-weight: 600; font-size: 15px; color: var(--on-bg); }
.username-time { font-size: 13px; color: var(--muted); display: flex; gap: 6px; }
.body { font-size: 15px; color: var(--on-bg); line-height: 1.6; white-space: pre-wrap; }
.images { margin-top: 10px; display: flex; flex-direction: column; gap: 8px; }
.post-img { width: 100%; border-radius: 12px; }
.actions { display: flex; gap: 20px; margin-top: 12px; }
.action-btn { font-size: 14px; color: var(--muted); padding: 4px 0; }
.action-btn:hover { color: var(--primary); }
</style>
